//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTests.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityTests.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;D&quot;: &quot;BQnmfzH3HKPN7XbuGz3/pYOQCNIKndE8yEgbmf84nOoBR+9VKskY6/8cgv9mqppTv+XOaO1YBBA6XwAtmfTmHSjWLFGYiqwONlZzaEzix+yXO0TJFKE/HSmuQ0LZCr9xv+PUDVDEHOFoPtQBIYOXDG0d9vfBqSlTlueL0xGO5RTrEwxTqEtSsrQv2ICrN7YdgIY2oIgArigYXDMUW+ItCeLotaW1Wpclw/Eu71hM8i81//bLNxULIJvWtvdlvEsAfrhJAL2wQMj7XMQMFSpzk4uj6qRcRGW6Kh9d1PaXg3BNpTLKzs4tkJ+AfPYlOOsLYsTOo1a8FXNaw00gdjXY/8N58aqTcDLrfUBPtEWLuqb91YnTQa9Eix331SgX3OhSnwyepIFxcfe3nDPXrWORZURXE+37t3rI1lXlQz9o5QZhaRtwTKGPbW5Flj3idOlic/LurOV/2kyzrEcpUgvBYKONX4MJmWOlCB5GHpxTchbxO/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample_RSA_keys {
            get {
                return ResourceManager.GetString("Sample_RSA_keys", resourceCulture);
            }
        }
    }
}
